services:
  - type: web
    name: quotetool
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_USE_TLS
        sync: false
      - key: SERVICE_PAY_NOW_URL
        value: https://collectcheckout.com/r/re7huwayxmaepcyzydrdtzaktt7yk6
